app:
    resource: '@AppBundle/Controller/'
    type: annotation
    # import routes from a controller class
Amis:
    resource: '@AppBundle/Controller/AmisController.php'
    type:     annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"